name: smile_shop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'
  #---------------- PACKAGES ----------------#
dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  dotted_line: ^3.2.3
  dropdown_button2: ^2.3.9
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.3
  geocoding: ^3.0.0
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  image_stack: ^2.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  loading_indicator: ^3.1.1
  location: ^7.0.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  record: ^5.2.0
  retrofit: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  voice_message_package: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.11

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  generate: true

  #---------------- ./ LOCAL ASSETS ----------------#
  assets:
    - assets/images/

  #---------------- ./ LOCAL FONTS ----------------#
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf
